FROM almalinux:9
#CMD ["ping", "google.com"] -->CMD can be overrid but not with entrypoint
#ENTRYPOINT ["ping", "google.com"] --> We can't overrid if we use entrypoint
CMD ["google.com"]
ENTRYPOINT ["ping"] # if use together CMD and ENTRYPOINT togather for better results 